/*
 * event_groups.h
 *
 *  Created on: Jul 13, 2020
 *      Author: gdbeckstein
 */

#ifndef MBED_AWS_CLIENT_LIBRARIES_AWS_OTA_FREERTOS_RETARGET_EVENT_GROUPS_H_
#define MBED_AWS_CLIENT_LIBRARIES_AWS_OTA_FREERTOS_RETARGET_EVENT_GROUPS_H_





#endif /* MBED_AWS_CLIENT_LIBRARIES_AWS_OTA_FREERTOS_RETARGET_EVENT_GROUPS_H_ */
