/*
 * queue.h
 *
 *  Created on: Jul 13, 2020
 *      Author: gdbeckstein
 */

#ifndef MBED_AWS_CLIENT_LIBRARIES_FREERTOS_RETARGET_QUEUE_H_
#define MBED_AWS_CLIENT_LIBRARIES_FREERTOS_RETARGET_QUEUE_H_





#endif /* MBED_AWS_CLIENT_LIBRARIES_FREERTOS_RETARGET_QUEUE_H_ */
